GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/8849

###
DELETE http://localhost:3001/api/persons/8849


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Aaron Hall",
    "number": 9546534555476
}