GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64f5e7e0cd37fe1ddf2a6dee

###
DELETE http://localhost:3001/api/persons/64f5fd29f1e5fcd20b81673d


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Aaron Hall",
    "number": 9546534555476
}

###
PUT http://localhost:3001/api/persons/64f5fcf6f1e5fcd20b816739
Content-Type: application/json

{
    "number": "999-86756756"
}

### Validation Checks
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 9546534555476
}
###
PUT http://localhost:3001/api/persons/64f5ee3d1469769ed5fa0cc4
Content-Type: application/json

{
}