GET http://localhost:3003/api/blogs


### OLD:: Creating new blog post
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Kuruma",
  "author": "Naruto1",
  "url": "www.somebloggers.com/kuruma",
  "userId": "64fd816055353acf45cd5263"
}
### Update blog author and likes
PUT http://localhost:3003/api/blogs/64ff30e6c970cc51f96f3997
Content-Type: : application/json

{
  "author": "Buggy",
  "likes": 45
}

### OLD:: Deleting blog post
DELETE http://localhost:3003/api/blogs/64ff37f18860812a20b0d917


### Users
GET http://localhost:3003/api/users

### User by Id
GET http://localhost:3003/api/users/64fd816055353acf45cd5263

### Create new User
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sample",
    "name": "testingUser",
    "password": "sekret"
}

### Login
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username" : "jermo",
  "password" : "jermo"
}

### Making an authorized Blog POST
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Implcm1vIiwiaWQiOiI2NGZkODE2MDU1MzUzYWNmNDVjZDUyNjMiLCJpYXQiOjE2OTU0ODIwNDAsImV4cCI6MTY5NTQ4NTY0MH0.4TktaVc9SEdTbQmXvkBFBa_TNwmqIEvU_AFHKkxCALY

{
  "title": "Token Authenticator Part II",
  "author": "Bearer",
  "url": "www.somebloggers.com/token-authenticator-part-ii",
  "userId": "64fd816055353acf45cd5263"
}

### Making Authorized Delete of blog
DELETE http://localhost:3003/api/blogs/64ff30e6c970cc51f96f3997
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Implcm1vIiwiaWQiOiI2NGZkODE2MDU1MzUzYWNmNDVjZDUyNjMiLCJpYXQiOjE2OTU0ODIwNDAsImV4cCI6MTY5NTQ4NTY0MH0.4TktaVc9SEdTbQmXvkBFBa_TNwmqIEvU_AFHKkxCALY